name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  end-to-end-tests:
    name: Run the end to end tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        working-directory: ./end2end
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: ./end2end
        run: npx playwright install --with-deps

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: Download and install tailwindcss binary
        run: npm install -D tailwindcss
      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.18.4/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - name: Start the app
        run: ./trunk serve

      - name: Run Playwright tests
        working-directory: ./end2end
        run: npx playwright test --reporter=line --max-failures=1
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: end2end/playwright-report/
          retention-days: 30

  test-code:
    name: Test Rust code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Machete
        uses: bnjbvr/cargo-machete@main

      - name: Check
        run: cargo check --verbose --all-targets --all-features
      - name: Run clippy checks
        run: cargo clippy -- -D warnings
      - name: Run fmt checks
        run: cargo fmt --check
      - name: Check for unused crates
        run: cargo machete
      - name: Run unit tests
        run: cargo test --verbose --all-targets
