name: Tests

on:
  workflow_call:

jobs:
  test:
    name: Test App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: trunk,wasm-bindgen
      - name: Machete
        uses: bnjbvr/cargo-machete@main # <-- For Cargo Machete
      - uses: actions/setup-node@v4 # <-- For the Playwright tests
        with:
          node-version: lts/*

      # code checks and unit tests
      - name: Check
        run: cargo check --verbose --all-targets --all-features
      - name: Run clippy checks
        run: cargo clippy -- -D warnings
      - name: Run fmt checks
        run: cargo fmt --check
      - name: Check for unused crates
        run: cargo machete
      - name: Run unit tests
        run: cargo test --verbose --all-targets

      # setup wasm and install playwright dependencies
      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: Install playwright dependencies
        working-directory: ./end2end
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: ./end2end
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./end2end
        run: npx playwright test --reporter=line --max-failures=1
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: end2end/playwright-report/
          retention-days: 30
