name: Tests

on:
  workflow_call:

jobs:
  end-to-end-tests:
    name: Run the end to end tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        working-directory: ./end2end
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: ./end2end
        run: npx playwright install --with-deps

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag name-picker
      - name: Run the app in the Docker image
        run: docker run --rm -d -p 3000:3000 --name test-run name-picker

      - name: Run Playwright tests
        working-directory: ./end2end
        run: npx playwright test --reporter=line --max-failures=1
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: end2end/playwright-report/
          retention-days: 30

  test-code:
    name: Test Rust code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Machete
        uses: bnjbvr/cargo-machete@main

      - name: Check
        run: cargo check --verbose --all-targets --all-features
      - name: Run clippy checks
        run: cargo clippy -- -D warnings
      - name: Run fmt checks
        run: cargo fmt --check
      - name: Check for unused crates
        run: cargo machete
      - name: Run unit tests
        run: cargo test --verbose --all-targets
